EmployeeManagement/EmployeeManagement/Controllers/SalaryController.cs
using EmployeeManagement.Context;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;
using EmployeeManagement.CustomSessions;
using System.Collections.Generic;
using EmployeeManagement.Models;
using System;
using EmpManagement.Models;
using EmployeeManagement.StaticDb;

namespace EmployeeManagement.Controllers
{
    public class SalaryController : Controller
    {
        EmployeeContext _employeeContext;
        public SalaryController(EmployeeContext employeeContext)
        {
            _employeeContext = employeeContext;
        }
             
        public async Task<IActionResult> Index()
        {
            ViewBag.ShowData = false;
            if (User.Identity.Name != null)
            {
                if (User.Identity.Name != "admin@nitor.com")
                {
                    if (User.Identity.Name == "accountant@nitor.com")
                    {
                      var data=(await _employeeContext.salaries.ToArrayAsync()).Where(c=>c.Role=="Staff");
                        return View(data);
                    }
                    else
                    {
                        var loggedInUser = HttpContext.Session.GetSessionObject<EmployeeModel>("loginUser");
                        var salaryByEmp = (await _employeeContext.salaries.ToArrayAsync()).Where(c => c.EmployeeId == loggedInUser.EmployeeId).ToList();
                        return View(salaryByEmp);
                    }
                }
                else
                {
                     return View("Index");
                }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        public async Task<IActionResult> Create()
        {
            var SStructureList = (await _employeeContext.salaryStructures.ToListAsync()).Where(c => c.Role == "Staff");
            var EmpSelect = new List<SelectListItem>();
            foreach (var item in SStructureList)
            {
                var empData = await _employeeContext.employees.FirstOrDefaultAsync(m => m.EmployeeId == item.EmployeeId);
                EmpSelect.Add(new SelectListItem(empData.FirstName + " " + empData.LastName, item.SalaryStructureId.ToString()));
            }
            ViewBag.SalaryStructureList = null;
            HttpContext.Session.SetSessionObject<List<SelectListItem>>("SalaryStructureList", EmpSelect);
            ViewBag.SalaryStructureList = EmpSelect;
            return View();
        }

        [HttpPost]
        public IActionResult GetSalaryStrucId(SalaryModel salaryStruct)
        {
            ViewBag.ShowData = true;
            MonthDb month = new MonthDb();
            ViewBag.MonthList = MonthDb.monthList;
            ViewBag.SalaryStructureList = HttpContext.Session.GetSessionObject<List<SelectListItem>>("SalaryStructureList");
            var getSalStructure = _employeeContext.salaryStructures.ToList().Where(c => c.SalaryStructureId == salaryStruct.SalaryStructureId).ToList()[0];

            salaryStruct.BasicPay = getSalStructure.BasicPay;
            salaryStruct.DA = getSalStructure.DA;
            salaryStruct.TA = getSalStructure.TA;
            salaryStruct.HRA = getSalStructure.HRA;
            salaryStruct.EmployeeId = getSalStructure.EmployeeId;
            salaryStruct.SalaryStructureId = getSalStructure.SalaryStructureId;
            var getLeavesCount = _employeeContext.leaves.ToList().Where(c => c.EmployeeId == getSalStructure.EmployeeId).Count();

            salaryStruct.LeavesTaken = getLeavesCount * Convert.ToInt32(LeaveCalculation.LeaveTakenCost);
            salaryStruct.OverTime = 0;
            salaryStruct.WeekendWorked = 0;

            salaryStruct.GrossSalary = salaryStruct.BasicPay + salaryStruct.DA + salaryStruct.TA + salaryStruct.HRA + salaryStruct.LeavesTaken;

            if (salaryStruct.GrossSalary > 50000)
            {
                salaryStruct.TDS = salaryStruct.GrossSalary * 10 / 100;
                salaryStruct.Total = salaryStruct.GrossSalary - salaryStruct.TDS;
            }

            HttpContext.Session.SetSessionObject<SalaryModel>("SelectedStaffDetails", salaryStruct);
            return View("Create", salaryStruct);
        }

        [HttpPost]
        public async Task<IActionResult> Create(SalaryModel salaryModel)
        {
            var data = HttpContext.Session.GetSessionObject<SalaryModel>("SelectedStaffDetails");
            salaryModel.EmployeeId = data.EmployeeId;
            salaryModel.SalaryStructureId = data.SalaryStructureId;
            salaryModel.Role = "Staff";
            if (ModelState.IsValid)
            {
                _employeeContext.salaries.Add(salaryModel);
                await _employeeContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateConsultant(SalaryModel salaryModel)
        {
            var data = HttpContext.Session.GetSessionObject<SalaryModel>("CSelectedStaffDetails");
            salaryModel.EmployeeId = data.EmployeeId;
            salaryModel.SalaryStructureId = data.SalaryStructureId;
            salaryModel.Role = "Consultant";
            if (ModelState.IsValid)
            {
                _employeeContext.salaries.Add(salaryModel);
                await _employeeContext.SaveChangesAsync();
                return RedirectToAction("IndexConsultant");
            }
          //  List<SalaryModel> sal = new List<SalaryModel>();
           // sal = (await _employeeContext.salaries.ToArrayAsync()).Where(c => c.Role == "Consultant").ToList();
            return View("IndexConsultant");
         }


        /// <summary>
        /// below functions for consultants
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> IndexConsultant()
        {
            List<SalaryModel> sal = new List<SalaryModel>();
            sal = (await _employeeContext.salaries.ToArrayAsync()).Where(c => c.Role == "Consultant").ToList();
            return View("IndexConsultant", sal);
        }


        public async Task<IActionResult> CreateConsultant()
        {
            var SStructureList = (await _employeeContext.salaryStructures.ToListAsync()).Where(c => c.Role == "Consultant");
            var EmpSelect = new List<SelectListItem>();
            foreach (var item in SStructureList)
            {
                var empData = await _employeeContext.consultants.FirstOrDefaultAsync(m => m.ConsultantId == item.EmployeeId);
                EmpSelect.Add(new SelectListItem(empData.ConsultantName, item.SalaryStructureId.ToString()));
            }
            ViewBag.CSalaryStructureList = null;
            HttpContext.Session.SetSessionObject<List<SelectListItem>>("CSalaryStructureList", EmpSelect);
            ViewBag.CSalaryStructureList = EmpSelect;
            return View();
        }
              
        [HttpPost]
        public IActionResult GetSalaryStrucIdForConsultant(SalaryModel salaryStruct)
        {
            ViewBag.ShowData = true;
            MonthDb month = new MonthDb();
            ViewBag.MonthList = MonthDb.monthList;
            ViewBag.CSalaryStructureList = HttpContext.Session.GetSessionObject<List<SelectListItem>>("CSalaryStructureList");
            var getSalStructure = _employeeContext.salaryStructures.ToList().Where(c => c.SalaryStructureId == salaryStruct.SalaryStructureId).ToList()[0];

            salaryStruct.BasicPay = getSalStructure.BasicPay;
            salaryStruct.DA = getSalStructure.DA;
            salaryStruct.TA = getSalStructure.TA;
            salaryStruct.HRA = getSalStructure.HRA;
            salaryStruct.EmployeeId = getSalStructure.EmployeeId;
            //    salaryStruct.SalaryStructureId = getSalStructure.SalaryStructureId;
            //  var getLeavesCount = _employeeContext.leaves.ToList().Where(c => c.EmployeeId == getSalStructure.EmployeeId).Count();

            // salaryStruct.LeavesTaken = getLeavesCount * Convert.ToInt32(LeaveCalculation.LeaveTakenCost);
            // salaryStruct.OverTime = 0;
            //  salaryStruct.WeekendWorked = 0;

            salaryStruct.GrossSalary = salaryStruct.BasicPay + salaryStruct.DA + salaryStruct.TA + salaryStruct.HRA;// + salaryStruct.LeavesTaken;

            if (salaryStruct.GrossSalary > 50000)
            {
                salaryStruct.TDS = salaryStruct.GrossSalary * 10 / 100;
                salaryStruct.Total = salaryStruct.GrossSalary - salaryStruct.TDS;
            }

            HttpContext.Session.SetSessionObject<SalaryModel>("CSelectedStaffDetails", salaryStruct);
            return View("CreateConsultant", salaryStruct);
        }

        //[HttpPost]
        //public IActionResult CreateConsultant(SalaryModel salaryStruct)
        //{
        //    ViewBag.ShowData = true;
        //    MonthDb month = new MonthDb();
        //    ViewBag.MonthList = MonthDb.monthList;
        //    ViewBag.SalaryStructureList = HttpContext.Session.GetSessionObject<List<SelectListItem>>("CSalaryStructureList");
        //    var getSalStructure = _employeeContext.salaryStructures.ToList().Where(c => c.SalaryStructureId == salaryStruct.SalaryStructureId).ToList()[0];

        //    salaryStruct.BasicPay = getSalStructure.BasicPay;
        //    salaryStruct.DA = getSalStructure.DA;
        //    salaryStruct.TA = getSalStructure.TA;
        //    salaryStruct.HRA = getSalStructure.HRA;
        //    salaryStruct.EmployeeId = getSalStructure.EmployeeId;
        //    salaryStruct.SalaryStructureId = getSalStructure.SalaryStructureId;
        //    var getLeavesCount = _employeeContext.leaves.ToList().Where(c => c.EmployeeId == getSalStructure.EmployeeId).Count();

EmployeeManagement/EmployeeManagement/Views/Salary/Create.cshtml
@model EmployeeManagement.Models.SalaryModel

@{
    ViewData["Title"] = "Create";
}

<div class="container-fluid">

    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-sm-6">
                    <h4>Create Salary Process</h4>
                </div>
                <div class="col-sm-6 pt-1 text-right"><a class="text-right text-dark" asp-action="Index">X</a></div>
            </div>
        </div>
        <div class="card-body">
            <form asp-action="GetSalaryStrucId">
                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label class="control-label">Employee</label>
                            <select id="testSelect" class="form-control" asp-for="@Model.SalaryStructureId"
                                    asp-items="@ViewBag.SalaryStructureList"></select>
                        </div>
                    </div>
                    <div class="col-sm-4 paddingt">
                        <input type="submit" value="Get Details" class="btn btn-primary" />
                    </div>
                </div>
            </form>
            @if (@ViewBag.ShowData==true)
            {
                <form asp-action="Create">
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label class="control-label">Year</label>
                                <input autocomplete="off" placeholder="Enter Year" asp-for="Year" class="form-control" />
                                <span asp-validation-for="Year" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label class="control-label">Month</label>
                                <select id="testSelect" class="form-control" asp-for="@Model.Month"
                                        asp-items="@ViewBag.MonthList"></select>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label asp-for="BasicPay" class="control-label"></label>
                                <input autocomplete="off" placeholder="Basic Pay" asp-for="BasicPay" class="form-control" />
                                <span asp-validation-for="BasicPay" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label asp-for="HRA" class="control-label"></label>
                                <input autocomplete="off" placeholder="HRA" asp-for="HRA" class="form-control" />
                                <span asp-validation-for="HRA" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label asp-for="TA" class="control-label"></label>
                                <input autocomplete="off" placeholder="TA" asp-for="TA" class="form-control" />
                                <span asp-validation-for="TA" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label asp-for="DA" class="control-label"></label>
                                <input autocomplete="off" placeholder="DA" asp-for="DA" class="form-control" />
                                <span asp-validation-for="DA" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label asp-for="OverTime" class="control-label"></label> (Per hour 200/-)
                                <input autocomplete="off" placeholder="Over Time" asp-for="OverTime" class="form-control" />
                                <span asp-validation-for="OverTime" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label asp-for="WeekendWorked" class="control-label"></label> (Per hour 300/-)
                                <input autocomplete="off" placeholder="Weekend Worked" asp-for="WeekendWorked" class="form-control" />
                                <span asp-validation-for="WeekendWorked" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label asp-for="LeavesTaken" class="control-label"></label>
                                <input autocomplete="off" placeholder="Leaves Taken" asp-for="LeavesTaken" class="form-control" />
                                <span asp-validation-for="LeavesTaken" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label asp-for="GrossSalary" class="control-label"></label>
                                <input autocomplete="off" placeholder="Gross Salary" asp-for="GrossSalary" class="form-control" />
                                <span asp-validation-for="GrossSalary" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label asp-for="TDS" class="control-label"></label>
                                <input autocomplete="off" placeholder="TDS Deduction" asp-for="TDS" class="form-control" />
                                <span asp-validation-for="TDS" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label asp-for="Total" class="control-label"></label>
                                <input autocomplete="off" placeholder="Gross Salary" asp-for="Total" class="form-control" />
                                <span asp-validation-for="Total" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4 paddingt">
                            <div class="form-group">
                                <input type="submit" value="Generate Salary" class="btn btn-primary" />
                            </div>
                        </div>
                    </div>
                </form>
            }
        </div>
    </div>

</div>

<style>
    .paddingt {
        padding-top: 1.9rem !important;
    }
</style>

EmployeeManagement/EmployeeManagement/Views/Salary/CreateConsultant.cshtml
@model EmployeeManagement.Models.SalaryModel

@{
    ViewData["Title"] = "CreateConsultant";
}


<div class="container-fluid">
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-sm-6">
                    <h4>Create Salary Process</h4>
                </div>
                <div class="col-sm-6 pt-1 text-right"><a class="text-right text-dark" asp-action="Index">X</a></div>
            </div>
        </div>
        <div class="card-body">
            <form asp-action="GetSalaryStrucIdForConsultant">
                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label class="control-label">Employee</label>
                            <select id="testSelect" class="form-control" asp-for="@Model.SalaryStructureId"
                                    asp-items="@ViewBag.CSalaryStructureList"></select>
                        </div>
                    </div>
                    <div class="col-sm-4 paddingt">
                        <input type="submit" value="Get Details" class="btn btn-primary" />
                    </div>
                </div>
            </form>
            @if (@ViewBag.ShowData == true)
            {
                <form asp-action="CreateConsultant" asp-controller="Salary">
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label class="control-label">Year</label>
                                <input autocomplete="off" placeholder="Enter Year" asp-for="Year" class="form-control" />
                                <span asp-validation-for="Year" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label class="control-label">Month</label>
                                <select id="testSelect" class="form-control" asp-for="@Model.Month"
                                        asp-items="@ViewBag.MonthList"></select>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label asp-for="BasicPay" class="control-label"></label>
                                <input autocomplete="off" placeholder="Basic Pay" asp-for="BasicPay" class="form-control" />
                                <span asp-validation-for="BasicPay" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label asp-for="HRA" class="control-label"></label>
                                <input autocomplete="off" placeholder="HRA" asp-for="HRA" class="form-control" />
                                <span asp-validation-for="HRA" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label asp-for="TA" class="control-label"></label>
                                <input autocomplete="off" placeholder="TA" asp-for="TA" class="form-control" />
                                <span asp-validation-for="TA" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label asp-for="DA" class="control-label"></label>
                                <input autocomplete="off" placeholder="DA" asp-for="DA" class="form-control" />
                                <span asp-validation-for="DA" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label asp-for="OverTime" class="control-label"></label> (Per hour 200/-)
                                <input autocomplete="off" placeholder="Over Time" asp-for="OverTime" class="form-control" />
                                <span asp-validation-for="OverTime" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label asp-for="WeekendWorked" class="control-label"></label> (Per hour 300/-)
                                <input autocomplete="off" placeholder="Weekend Worked" asp-for="WeekendWorked" class="form-control" />
                                <span asp-validation-for="WeekendWorked" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label asp-for="LeavesTaken" class="control-label"></label>
                                <input autocomplete="off" placeholder="Leaves Taken" asp-for="LeavesTaken" class="form-control" />
                                <span asp-validation-for="LeavesTaken" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label asp-for="GrossSalary" class="control-label"></label>
                                <input autocomplete="off" placeholder="Gross Salary" asp-for="GrossSalary" class="form-control" />
                                <span asp-validation-for="GrossSalary" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label asp-for="TDS" class="control-label"></label>
                                <input autocomplete="off" placeholder="TDS Deduction" asp-for="TDS" class="form-control" />
                                <span asp-validation-for="TDS" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label asp-for="Total" class="control-label"></label>
                                <input autocomplete="off" placeholder="Gross Salary" asp-for="Total" class="form-control" />
                                <span asp-validation-for="Total" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4 paddingt">
                            <div class="form-group">
                                <input type="submit" value="Generate Salary" class="btn btn-primary" />
                            </div>
                        </div>
                    </div>
                </form>
            }
        </div>
    </div>
</div>
 

<style>
    .paddingt {
        padding-top: 1.9rem !important;
    }
</style>

EmployeeManagement/EmployeeManagement/Views/Salary/Index.cshtml
@model IEnumerable<EmployeeManagement.Models.SalaryModel>

@{
    ViewData["Title"] = "Index";
}


<div class="container-fluid">
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-sm-6">
                    <h4>Salary</h4>
                </div>
                @if (User.Identity.IsAuthenticated)
                {
                    if (User.IsInRole("Accountant"))
                    {
                        <div class="col-sm-6 text-right"><a asp-action="Create">Create New</a></div>
                    }
                }

            </div>
        </div>
        <div class="card-body">

            <table class="table">
                <thead>
                    <tr>
                        @*<th>
                        @Html.DisplayNameFor(model => model.Role)
                    </th>*@
                        @*<th>
                        @Html.DisplayNameFor(model => model.SalaryStructureId)
                    </th>*@
                        <th>
                            @Html.DisplayNameFor(model => model.EmployeeId)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.BasicPay)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.HRA)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.TA)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.DA)
                        </th>
                        @*<th>
                            @Html.DisplayNameFor(model => model.OverTime)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.LeavesTaken)
                        </th>*@
                        @*<th>
                            @Html.DisplayNameFor(model => model.WeekendWorked)
                        </th>*@
                        <th>
                            @Html.DisplayNameFor(model => model.GrossSalary)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.TDS)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Total)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            @*<td>
                            @Html.DisplayFor(modelItem => item.Role)
                        </td>*@
                            @*<td>
                            @Html.DisplayFor(modelItem => item.SalaryStructureId)
                        </td>*@
                            <td>
                                @Html.DisplayFor(modelItem => item.EmployeeId)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.BasicPay)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.HRA)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.TA)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.DA)
                            </td>
                            @*<td>
                                @Html.DisplayFor(modelItem => item.OverTime)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.LeavesTaken)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.WeekendWorked)
                            </td>*@
                            <td>
                                @Html.DisplayFor(modelItem => item.GrossSalary)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.TDS)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Total)
                            </td>
                            <td>
                                <a asp-action="Edit" asp-route-id="@item.SalaryId">Edit</a> |
                                <a asp-action="Details" asp-route-id="@item.SalaryId">Details</a> |
                                <a asp-action="Delete" asp-route-id="@item.SalaryId">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
 