EmployeeManagement/EmployeeManagement/Controllers/LeaveController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EmployeeManagement.Context;
using EmployeeManagement.Models;
using EmployeeManagement.CustomSessions;
using EmpManagement.Models;
using Microsoft.AspNetCore.Authorization;

namespace EmployeeManagement.Controllers
{
    [Authorize]
    public class LeaveController : Controller
    {
        private readonly EmployeeContext _context;

        public LeaveController(EmployeeContext context)
        {
            _context = context;
        }

        // GET: Leave
        public async Task<IActionResult> Index()
        {
            if (User.Identity.Name != null)
            {
                if (User.Identity.Name != "admin@nitor.com")
                {
                    var loggedInUser = HttpContext.Session.GetSessionObject<EmployeeModel>("loginUser");

                    var leavesByEmp = (await _context.leaves.ToArrayAsync()).Where(c => c.EmployeeId == loggedInUser.EmployeeId).ToList();
                    //   var await _context.leaves.ToListAsync()
                    return View(leavesByEmp);
                }
                else
                {
                    List<LeaveApproveModel> leaveApproveList = await GetLeaveForApprove();
                    return View("LeaveApproveIndex", leaveApproveList);
                }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        public async Task<List<LeaveApproveModel>> GetLeaveForApprove()
        {
            List<LeaveApproveModel> leaveApproveList = new List<LeaveApproveModel>();
            var leavesByEmp = (await _context.leaves.ToArrayAsync()).ToList();
            foreach (var item in leavesByEmp)
            {
                var emp = (await _context.employees.ToListAsync()).Where(c => c.EmployeeId == item.EmployeeId).ToList()[0];
                leaveApproveList.Add(new LeaveApproveModel
                {
                    EmployeeId = item.EmployeeId,
                    EmployeeName = emp.FirstName + " " + emp.LastName,
                    LeaveId = item.LeaveId,
                    LeaveType = item.LeaveType,
                    LeaveDateFrom = item.LeaveDateFrom,
                    LeaveDateTo = item.LeaveDateTo,
                    Status = item.Status,
                    Remark = item.Remark,
                    ApproveRemark=item.ApproveRemark,
                    LeaveApprovedDate=item.LeaveApprovedDate
                });
            }
            HttpContext.Session.SetSessionObject<List<LeaveApproveModel>>("leaveApproveList", leaveApproveList);
            return leaveApproveList;
        }

        // GET: Leave/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var leaveModel = await _context.leaves
                .FirstOrDefaultAsync(m => m.LeaveId == id);
            if (leaveModel == null)
            {
                return NotFound();
            }

            return View(leaveModel);
        }

        // GET: Leave/Create
        public IActionResult Create()
        {
            var dateAndTime = DateTime.Now;
            ViewBag.TodayDate = dateAndTime.Date;
            return View();
        }

        // POST: Leave/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LeaveId,EmployeeId,LeaveType,LeaveDateFrom,LeaveDateTo,Status,Remark")] LeaveModel leaveModel)
        {
            ViewBag.loginUser = HttpContext.Session.GetSessionObject<EmployeeModel>("loginUser");
            leaveModel.EmployeeId = ViewBag.loginUser.EmployeeId;
            leaveModel.Status = "New";
            if (ModelState.IsValid)
            {
                _context.Add(leaveModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(leaveModel);
        }

        // GET: Leave/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var leaveModel = await _context.leaves.FindAsync(id);
            if (leaveModel == null)
            {
                return NotFound();
            }
            return View(leaveModel);
        }

        public IActionResult LeaveApprove(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var data = HttpContext.Session.GetSessionObject<List<LeaveApproveModel>>("leaveApproveList");

            var leaveModel = data.Where(c => c.LeaveId == id).FirstOrDefault();
            if (leaveModel == null)
            {
                return NotFound();
            }
            return View("LeaveApprove", leaveModel);
        }

        [HttpPost]
        public async Task<IActionResult> LeaveApprove(int id, LeaveApproveModel leaveApprove)
        {
            if (leaveApprove.ApproveRemark != null)
            {
                var data = HttpContext.Session.GetSessionObject<List<LeaveApproveModel>>("leaveApproveList");

                var tempLeave = data.Where(c => c.LeaveId == id).FirstOrDefault();

                var dateAndTime = DateTime.Now;
                var date = dateAndTime.Date;
                LeaveModel leaveModel = new LeaveModel()
                {
                    LeaveApprovedDate = date,
                    LeaveId = id,
                    Status = "Approved",
                    ApproveRemark = leaveApprove.ApproveRemark,
                    LeaveDateFrom = tempLeave.LeaveDateFrom,
                    LeaveDateTo = tempLeave.LeaveDateTo,
                    Remark = tempLeave.Remark,
                    EmployeeId = tempLeave.EmployeeId,
                    LeaveType = tempLeave.LeaveType

                };

                _context.leaves.Update(leaveModel);
                await _context.SaveChangesAsync();
            }
            List<LeaveApproveModel> leaveApproveList = await GetLeaveForApprove();
            return View("LeaveApproveIndex", leaveApproveList);
        }


        // POST: Leave/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LeaveId,EmployeeId,LeaveType,LeaveDateFrom,LeaveDateTo,Status,Remark")] LeaveModel leaveModel)
        {
            if (id != leaveModel.LeaveId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(leaveModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LeaveModelExists(leaveModel.LeaveId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(leaveModel);
        }

        // GET: Leave/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var leaveModel = await _context.leaves
                .FirstOrDefaultAsync(m => m.LeaveId == id);
            if (leaveModel == null)
            {
                return NotFound();
            }

            return View(leaveModel);
        }

        // POST: Leave/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var leaveModel = await _context.leaves.FindAsync(id);
            _context.leaves.Remove(leaveModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LeaveModelExists(int id)
        {
            return _context.leaves.Any(e => e.LeaveId == id);
        }
    }
}

EmployeeManagement/EmployeeManagement/Controllers/RoleController.cs
using EmployeeManagement.Context;
using EmployeeManagement.CustomSessions;
using EmpManagement.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;

namespace EmployeeManagement.Controllers
{
    public class RoleController : Controller
    {
        private readonly EmployeeContext _context;
        private RoleManager<IdentityRole> _roleManager;
        private readonly SignInManager<IdentityUser> _signInManager;
        public RoleController(RoleManager<IdentityRole> roleMgr, EmployeeContext context, SignInManager<IdentityUser> signInManager)
        {
            _roleManager = roleMgr;
            _context = context;
            _signInManager = signInManager;
        }

        // public ViewResult Index() => View(_roleManager.Roles);

        public ViewResult Index() => View(_roleManager.Roles);

        //// GET: Role/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Required] string RoleName)
        {
            if (ModelState.IsValid)
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(RoleName));
                if (result.Succeeded)
                    return RedirectToAction("Index");
                else
                    Errors(result);
            }
            return View(RoleName);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
                if (result.Succeeded)
                    return RedirectToAction("Index");
                else
                    Errors(result);
            }
            else
                ModelState.AddModelError("", "No role found");
            return View("Index", _roleManager.Roles);

        }

        public async Task<IActionResult> AssignRole()
        {
            var empList = (await _signInManager.UserManager.Users.ToListAsync());
            //var empList = (await _context.employees.ToListAsync());
            var roleList = (await _roleManager.Roles.ToListAsync());

            var RoleSelect = new List<SelectListItem>();
            foreach (var item in roleList)
            {
                RoleSelect.Add(new SelectListItem(item.Name, item.Id.ToString()));
            }
            ViewBag.RoleList = null;
            HttpContext.Session.SetSessionObject<List<SelectListItem>>("RoleList", RoleSelect);
            ViewBag.RoleList = RoleSelect;

            var EmployeeSelect = new List<SelectListItem>();
            foreach (var item in empList)
            {
                EmployeeSelect.Add(new SelectListItem(item.UserName, item.Id.ToString()));
            }
            ViewBag.EmployeeList = null;
            HttpContext.Session.SetSessionObject<List<SelectListItem>>("EmployeeList", EmployeeSelect);
            ViewBag.EmployeeList = EmployeeSelect;


            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AssignRole(RoleModel roleModel)
        {
            if (ModelState.IsValid)
            {
                var empList = (await _signInManager.UserManager.Users.ToListAsync()).Find(c => c.Id == Convert.ToString(roleModel.UserId));
                var roleInfo = (await _roleManager.FindByIdAsync(roleModel.RoleId));
                IdentityResult result = await _signInManager.UserManager.AddToRoleAsync(empList, roleInfo.Name);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                    Errors(result);
                // else
                //    ModelState.AddModelError("", "No role found");
                return View("Index", _roleManager.Roles);
            }
            else
            {
                ModelState.AddModelError("", "No role found");
                return View("Index", _roleManager.Roles);
            }
        }

        private void Errors(IdentityResult result)
        {
            foreach (IdentityError error in result.Errors)
                ModelState.AddModelError("", error.Description);
        }

        //// GET: Role
        //public async Task<IActionResult> Index()
        //{
        //    return View(await _context.roles.ToListAsync());
        //}

        //// GET: Role/Details/5
        //public async Task<IActionResult> Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var roleModel = await _context.roles
        //        .FirstOrDefaultAsync(m => m.RoleId == id);
        //    if (roleModel == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(roleModel);
        //}



        //// POST: Role/Create
        //// To protect from overposting attacks, enable the specific properties you want to bind to, for 
        //// more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("RoleId,RoleName")] RoleModel roleModel)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _context.Add(roleModel);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(roleModel);
        //}

        //// GET: Role/Edit/5
        //public async Task<IActionResult> Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var roleModel = await _context.roles.FindAsync(id);
        //    if (roleModel == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(roleModel);
        //}

        //// POST: Role/Edit/5
        //// To protect from overposting attacks, enable the specific properties you want to bind to, for 
        //// more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int id, [Bind("RoleId,RoleName")] RoleModel roleModel)
        //{
        //    if (id != roleModel.RoleId)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            _context.Update(roleModel);
        //            await _context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            if (!RoleModelExists(roleModel.RoleId))
        //            {
        //                return NotFound();
        //            }
        //            else
        //            {
        //                throw;
        //            }
        //        }
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(roleModel);
        //}

        //// GET: Role/Delete/5
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var roleModel = await _context.roles
        //        .FirstOrDefaultAsync(m => m.RoleId == id);
        //    if (roleModel == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(roleModel);
        //}

        //// POST: Role/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(int id)
        //{
        //    var roleModel = await _context.roles.FindAsync(id);
        //    _context.roles.Remove(roleModel);
        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        //private bool RoleModelExists(int id)
        //{
        //    return _context.roles.Any(e => e.RoleId == id);
        //}


    }
}

EmployeeManagement/EmployeeManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Employee Management</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light customheader border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">HRMS</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Employee" asp-action="Index">Profile</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Leave" asp-action="Index">Leaves</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Investment" asp-action="Index">Investments</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Salary" asp-action="Index">My Pay</a>
                                </li>
                                <li class="dropdown menuStyl nav-item">
                                    <a href="#" class="text-white dropdown-toggle" data-toggle="dropdown">Admin<b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li class="nav-item submenu">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Role</a>
                                        </li>
                                        <li class="nav-item submenu">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Consultant" asp-action="Index">Consultant</a>
                                        </li>
                                    </ul>
                                </li>
                            }
                            if (User.IsInRole("Consultant"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Consultant" asp-action="Index">Profile</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Salary" asp-action="Index">My Pay</a>
                                </li>

                            }
                            if (User.IsInRole("Accountant"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Employee" asp-action="Index">Profile</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Leave" asp-action="Index">Leaves</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Investment" asp-action="Index">Investments</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Salary" asp-action="Index">My Pay</a>
                                </li>
                                <li class="dropdown menuStyl nav-item">
                                    <a href="#" class="text-white dropdown-toggle" data-toggle="dropdown">Payroll<b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li class="nav-item submenu">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="SalaryStructure" asp-action="Index">Salary Structure</a>
                                        </li>
                                        <li class="nav-item submenu">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Salary" asp-action="Index">Salary Process (Staff) </a>
                                        </li>
                                        <li class="nav-item submenu">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Salary" asp-action="IndexConsultant">Salary Process (Consultant)</a>
                                        </li>
                                    </ul>
                                </li>
                            }
                            if (User.IsInRole("Staff"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Employee" asp-action="Index">Profile</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Leave" asp-action="Index">Leaves</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Investment" asp-action="Index">Investments</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Salary" asp-action="Index">My Pay</a>
                                </li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - HRMS
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>


<style>
    .menuStyl {
        padding-top: 8px;
        padding-left: 8px;
    }

    a:hover {
        color: #0056b3;
        text-decoration: auto !important;
    }

    .submenu:hover {
        background: #e7e7e7;
    }

    .customheader {
        background-color: #0D2137 !important;
    }
</style>